version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ledger
      POSTGRES_USER: ledger_admin
      POSTGRES_PASSWORD: "123456"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
